# Generated by Django 3.2.4 on 2021-06-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('names', models.CharField(max_length=100)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('interests', models.CharField(max_length=300)),
            ],
        ),
    ]
